function changeColor(num){
    document.body.style.backgroundColor= nameColor[num];
    document.getElementById("head1").innerHTML = nameColor[num];
    //copy color to clipboard
    var textA=document.createElement('textarea');
    textA.value = nameColor[num];
    document.body.appendChild(textA);
    textA.select();
    document.execCommand("copy");
    document.body.removeChild(textA);
}
var nameColor = ['Pink','LightPink','HotPink','DeepPink','PaleVioletRed','MediumVioletRed','LightSalmon','Salmon','DarkSalmon','LightCoral','IndianRed','Crimson','Firebrick','DarkRed','Red','OrangeRed','Tomato','Coral','DarkOrange','Orange','Yellow','LightYellow','LemonChiffon','LightGoldenrodYellow','PapayaWhip','Moccasin','PeachPuff','PaleGoldenrod','Khaki','DarkKhaki','Gold','Cornsilk','BlanchedAlmond','Bisque','NavajoWhite','Wheat','Burlywood','Tan','RosyBrown','SandyBrown','Goldenrod','DarkGoldenrod','Peru','Chocolate','SaddleBrown','Sienna','Brown','Maroon','DarkOliveGreen','Olive','OliveDrab','YellowGreen','LimeGreen','Lime','LawnGreen','Chartreuse','GreenYellow','SpringGreen','MediumSpringGreen','LightGreen','PaleGreen','DarkSeaGreen','MediumAquamarine','MediumSeaGreen','SeaGreen','ForestGreen','Green','DarkGreen','Aqua','Cyan','LightCyan','PaleTurquoise','Aquamarine','Turquoise','MediumTurquoise','DarkTurquoise','LightSeaGreen','CadetBlue','DarkCyan','Teal','LightSteelBlue','PowderBlue','LightBlue','SkyBlue','LightSkyBlue','DeepSkyBlue','DodgerBlue','CornflowerBlue','SteelBlue','RoyalBlue','Blue','MediumBlue','DarkBlue','Navy','MidnightBlue','Lavender','Thistle','Plum','Violet','Orchid','Fuchsia','Magenta','MediumOrchid','MediumPurple','BlueViolet','DarkViolet','DarkOrchid','DarkMagenta','Purple','Indigo','DarkSlateBlue','SlateBlue','MediumSlateBlue','White','Snow','Honeydew','MintCream','Azure','AliceBlue','GhostWhite','WhiteSmoke','Seashell','Beige','OldLace','FloralWhite','Ivory','AntiqueWhite','Linen','LavenderBlush','MistyRose','Gainsboro','LightGray','Silver','DarkGray','Gray','DimGray','LightSlateGray','SlateGray','DarkSlateGray','Black'];
for(var i=0;i<nameColor.length;i++){
    document.write('<button class="btn '+'color'+nameColor[i]+'" onclick="changeColor('+i+')" id="color'+i+'">'+nameColor[i]+'</button>');
    if(i==5||i==14||i==19||i==30||i==47||i==67||i==79||i==94||i==112||i==129){
        document.write('<br><br><hr color="white"><br><br>');
    }
}

/*
Pink
LightPink
HotPink
DeepPink
PaleVioletRed
MediumVioletRed
LightSalmon
Salmon
DarkSalmon
LightCoral
IndianRed
Crimson
Firebrick
DarkRed
Red
OrangeRed
Tomato
Coral
DarkOrange
Orange
Yellow
LightYellow
LemonChiffon
LightGoldenrodYellow
PapayaWhip
Moccasin
PeachPuff
PaleGoldenrod
Khaki
DarkKhaki
Gold
Cornsilk
BlanchedAlmond
Bisque
NavajoWhite
Wheat
Burlywood
Tan
RosyBrown
SandyBrown
Goldenrod
DarkGoldenrod
Peru
Chocolate
SaddleBrown
Sienna
Brown
Maroon
DarkOliveGreen
Olive
OliveDrab
YellowGreen
LimeGreen
Lime
LawnGreen
Chartreuse
GreenYellow
SpringGreen
MediumSpringGreen
LightGreen
PaleGreen
DarkSeaGreen
MediumAquamarine
MediumSeaGreen
SeaGreen
ForestGreen
Green
DarkGreen
Aqua
Cyan
LightCyan
PaleTurquoise
Aquamarine
Turquoise
MediumTurquoise
DarkTurquoise
LightSeaGreen
CadetBlue
DarkCyan
Teal
LightSteelBlue
PowderBlue
LightBlue
SkyBlue
LightSkyBlue
DeepSkyBlue
DodgerBlue
CornflowerBlue
SteelBlue
RoyalBlue
Blue
MediumBlue
DarkBlue
Navy
MidnightBlue
Lavender
Thistle
Plum
Violet
Orchid
Fuchsia
Magenta
MediumOrchid
MediumPurple
BlueViolet
DarkViolet
DarkOrchid
DarkMagenta
Purple
Indigo
DarkSlateBlue
SlateBlue
MediumSlateBlue 
White
Snow
Honeydew
MintCream
Azure
AliceBlue
GhostWhite
WhiteSmoke
Seashell
Beige
OldLace
FloralWhite
Ivory
AntiqueWhite
Linen
LavenderBlush
MistyRose
Gainsboro
LightGray
Silver
DarkGray
Gray
DimGray
LightSlateGray
SlateGray
DarkSlateGray
Black
--------------------------
'Pink',
'LightPink',
'HotPink',
'DeepPink',
'PaleVioletRed',
'MediumVioletRed',
'LightSalmon',
'Salmon',
'DarkSalmon',
'LightCoral',
'IndianRed',
'Crimson',
'Firebrick',
'DarkRed',
'Red',
'OrangeRed',
'Tomato',
'Coral',
'DarkOrange',
'Orange',
'Yellow',
'LightYellow',
'LemonChiffon',
'LightGoldenrodYellow',
'PapayaWhip',
'Moccasin',
'PeachPuff',
'PaleGoldenrod',
'Khaki',
'DarkKhaki',
'Gold',
'Cornsilk',
'BlanchedAlmond',
'Bisque',
'NavajoWhite',
'Wheat',
'Burlywood',
'Tan',
'RosyBrown',
'SandyBrown',
'Goldenrod',
'DarkGoldenrod',
'Peru',
'Chocolate',
'SaddleBrown',
'Sienna',
'Brown',
'Maroon',
'DarkOliveGreen',
'Olive',
'OliveDrab',
'YellowGreen',
'LimeGreen',
'Lime',
'LawnGreen',
'Chartreuse',
'GreenYellow',
'SpringGreen',
'MediumSpringGreen',
'LightGreen',
'PaleGreen',
'DarkSeaGreen',
'MediumAquamarine',
'MediumSeaGreen',
'SeaGreen',
'ForestGreen',
'Green',
'DarkGreen',
'Aqua',
'Cyan',
'LightCyan',
'PaleTurquoise',
'Aquamarine',
'Turquoise',
'MediumTurquoise',
'DarkTurquoise',
'LightSeaGreen',
'CadetBlue',
'DarkCyan',
'Teal',
'LightSteelBlue',
'PowderBlue',
'LightBlue',
'SkyBlue',
'LightSkyBlue',
'DeepSkyBlue',
'DodgerBlue',
'CornflowerBlue',
'SteelBlue',
'RoyalBlue',
'Blue',
'MediumBlue',
'DarkBlue',
'Navy',
'MidnightBlue',
'Lavender',
'Thistle',
'Plum',
'Violet',
'Orchid',
'Fuchsia',
'Magenta',
'MediumOrchid',
'MediumPurple',
'BlueViolet',
'DarkViolet',
'DarkOrchid',
'DarkMagenta',
'Purple',
'Indigo',
'DarkSlateBlue',
'SlateBlue',
'MediumSlateBlue',
'White',
'Snow',
'Honeydew',
'MintCream',
'Azure',
'AliceBlue',
'GhostWhite',
'WhiteSmoke',
'Seashell',
'Beige',
'OldLace',
'FloralWhite',
'Ivory',
'AntiqueWhite',
'Linen',
'LavenderBlush',
'MistyRose',
'Gainsboro',
'LightGray',
'Silver',
'DarkGray',
'Gray',
'DimGray',
'LightSlateGray',
'SlateGray',
'DarkSlateGray',
'Black'
*/
